version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: obsidian-telegram-bot
    restart: unless-stopped
    volumes:
      - ./vault:/app/vault
      - ./recurring_events:/app/recurring_events
      - ./conversation_history.json:/app/conversation_history.json
      - ./global_recurring_events.json:/app/global_recurring_events.json
      - ./.env:/app/.env
    environment:
      - TZ=UTC
    # You can uncomment and use this section if you want to specify env vars directly instead of .env file
    # environment:
    #   - GEMINI_API_KEY=your_gemini_api_key
    #   - GEMINI_MODEL_NAME=gemini-2.0-flash
    #   - TELEGRAM_BOT_TOKEN=your_telegram_bot_token
    #   - TELEGRAM_USER_ID=your_user_id
    #   - OBSIDIAN_DAILY_NOTES_FOLDER=Daily
    #   - OBSIDIAN_VAULT_PATH=/app/vault 